sudo: false

language: python

python:
   - "2.7"

before_install:
    - pip install --upgrade pip

install:
    - pip install autopep8
    - pip install coverage
    - pip install numpy
    - pip install pylint
    - pip install flask
    - pip install flask_sqlalchemy
    - pip install flask_restless
    - pip install requests
    - pip install iso639
    - pip install psycopg2
    - pip install -e .

before_script:
    - uname -a
    - printenv | sort
    - make versions

script:
    - date
    - ls -al
    - make test