FORMAT: 1A
HOST: http://streamGlean.me/api

# streamGlean

streamGlean is a simple API allowing consumers to view users, games, teams, and communities in the streamGlean database.

## Users Collection [/user]

### List All Users [GET]
This will return all the user objects in the streamGlean database.

+ Response 200 (application/json)

        {
            "num_results": 2, 
            "objects": [
                {
                    "community_id": "59c7de59-be82-4e11-906c-b9ce9183023a", 
                    "created": "2015-08-23T12:53:41", 
                    "description": "Streameur Amateur, je stream pour le plaisir de partager ce que je fais,j'esp\u00e8re que vous allez aimer.", 
                    "followers": 112, 
                    "game_id": 41928, 
                    "id": "100348951", 
                    "image_url": "https://static-cdn.jtvnw.net/jtv_user_pictures/haldamart-profile_image-53ef3ce9da8bf5b7-300x300.jpeg", 
                    "language": "French", 
                    "name": "Haldamart", 
                    "team_ids": null, 
                    "updated": "2017-07-05T21:04:32", 
                    "url": "https://www.twitch.tv/haldamart", 
                    "views": 2433
                },
                {
                    "community_id": null, 
                    "created": "2010-01-18T21:23:10", 
                    "description": "BladeMaster's Broadcast Club - PIPe Gaming Channel. For more info click here http://steamcommunity.com/groups/bladesbroadcastclub", 
                    "followers": 5122, 
                    "game_id": 54231, 
                    "id": "10047028", 
                    "image_url": "https://static-cdn.jtvnw.net/jtv_user_pictures/pipe-profile_image-a3062856f29e1a08-300x300.png", 
                    "language": "English", 
                    "name": "PIPe", 
                    "team_ids": [
                        10
                    ], 
                        "updated": "2017-07-06T03:32:25", 
                        "url": "https://www.twitch.tv/pipe", 
                        "views": 652951
                }
            ]    
        }   

## Games Collection [/game]

### List All Games [GET]
This will return all the game objects in the streamGlean database.

+ Response 200 (application/json)

        {
            "num_results": 2, 
            "objects": [
                {
                    "community_ids": null, 
                    "description": "X-COM: UFO Defense is a genre-defining strategy game released in 1994 combining both strategic and tactical gameplay.", 
                    "genres": [
                        "Strategy"
                    ], 
                    "id": 196, 
                    "image_url": "https://www.giantbomb.com/api/image/scale_small/2370096-xcombox.jpg", 
                    "name": "X-COM: UFO Defense", 
                    "platforms": [
                        "Amiga", 
                        "PlayStation", 
                        "Amiga CD32", 
                        "PC"
                    ], 
                    "rating": "K-A", 
                    "release_date": "1993-12-31T00:00:00", 
                    "team_ids": [
                        10
                    ], 
                    "user_ids": [
                        "109786824"
                    ]
                }, 
                {
                    "community_ids": null, 
                    "description": "Incantion is a fanntasy sidescroller made quite late in the life of the SNES. Watchoo know about wand-shooting?", 
                    "genres": [
                        "Action", 
                        "Platformer"
                    ], 
                    "id": 450, 
                    "image_url": "https://www.giantbomb.com/api/image/scale_small/492406-915491_28303_front.jpg", 
                    "name": "Incantation", 
                    "platforms": [
                        "Super Nintendo Entertainment System"
                    ], 
                    "rating": "K-A", 
                    "release_date": "1996-11-30T00:00:00", 
                    "team_ids": [
                        10
                    ], 
                    "user_ids": [
                        "20224161"
                    ]
                }
            ]    
        }
## Teams Collection [/team]

### List All Teams [GET]
This will return all the team objects in the streamGlean database.

+ Response 200 (application/json)

        {
            "num_results": 3, 
            "objects": [
                {
                    "created": "2011-10-11T22:49:05", 
                    "game_ids": [
                        25142, 
                        8852, 
                        16407, 
                        55371
                    ], 
                    "id": 1, 
                    "image_url": "https://static-cdn.jtvnw.net/jtv_user_pictures/team-testteam-team_logo_image-46943237490be5e7-300x300.jpeg", 
                    "info": "I love working for Twitch!\n\n\n\n", 
                    "name": "test", 
                    "updated": "2013-10-17T23:29:42", 
                    "user_ids": [
                        "25735425", 
                        "15413654", 
                        "13162485", 
                        "5629796", 
                        "21427717", 
                        "9796851", 
                        "3799340", 
                        "387858", 
                        "10377111", 
                        "13329726", 
                        "12816873", 
                        "12698729", 
                        "28428378", 
                        "188563", 
                        "30736534"
                    ]
                },
                {
                    "created": "2011-10-25T23:32:49", 
                    "game_ids": [], 
                    "id": 7, 
                    "image_url": "https://static-cdn.jtvnw.net/jtv_user_pictures/xarth/404_user_70x70.png", 
                    "info": "Team Carbon - Gears of War 3", 
                    "name": "Carbon", 
                    "updated": "2013-05-24T00:17:10", 
                    "user_ids": [
                        "19968416"
                    ]
                },
                {
                    "created": "2011-10-11T23:59:43", 
                    "game_ids": [
                        48754, 
                        25038, 
                        32887, 
                        48320, 
                        54979, 
                        42905, 
                        17743, 
                        52633, 
                        24024, 
                        54166, 
                        27267
                    ], 
                    "id": 2, 
                    "image_url": "https://static-cdn.jtvnw.net/jtv_user_pictures/team-eg-team_logo_image-360dfbc1fd826286-300x300.png", 
                    "info": "Team Info\r\n\r\n", 
                    "name": "Evil Geniuses", 
                    "updated": "2017-01-21T11:15:27", 
                    "user_ids": [
                        "119089037", 
                        "43061645", 
                        "23364603", 
                        "32556389", 
                        "9635121", 
                        "25095238", 
                        "21672866", 
                        "75587512", 
                        "22364523", 
                        "65389928", 
                        "23113554", 
                        "19306662", 
                        "23951758", 
                        "32420547", 
                        "74266426", 
                        "88514677", 
                        "22783448", 
                        "10328157", 
                        "25644379", 
                        "58351323", 
                        "13326547"
                    ]
                }
            ]    
        }

## Communities Collection [/community]

### List All Communities [GET]
This will return all the community objects in the streamGlean database.

+ Response 200 (application/json)

        {
            "num_results": 2, 
            "objects": [
                {
                    "description": "The Call of Duty Community on Twitch.  Open to any game in the Series.\nThe Family of Call of Duty Communities:\n* [Modern Warfare Series](https://www.twitch.tv/communities/ModernWarfare)", 
                    "game_id": 39193, 
                    "id": "05ff5349-d4f5-4b98-92ab-6e09ab705bed", 
                    "image_url": "https://static-cdn.jtvnw.net/community-images/05ff5349-d4f5-4b98-92ab-6e09ab705bed/8c63eef1-c2ad-4388-8b60-90d5a5e75cb5-185x258.png", 
                    "language": "English", 
                    "name": "Call-Of-Duty", 
                    "owner_id": "1645379", 
                    "rules": "* Be excellent to each other\n* Respect the Twitch Community Guidelines\n* No bullying or harassment\n* Have fun!\n"
                },  
                {
                    "description": "Viewers:\nThis community is a great place to find awesome broadcasters who have been following the development of PUBG since day one. You\u2019ll find a mix of streamers that range from casual to competitive and everything in between.\n Owner :ErykInFloZ", 
                    "game_id": null, 
                    "id": "01d41280-9332-4f54-b77a-a20f577beade", 
                    "image_url": "https://static-cdn.jtvnw.net/community-images/01d41280-9332-4f54-b77a-a20f577beade/6660ab7f-3391-426e-acb4-1b61575ca982-185x258.jpeg", 
                    "language": "English", 
                    "name": "PLAYERUNKNOWNBATTLEGROUND", 
                    "owner_id": "116814743", 
                    "rules": "No Spamming\nMust Have Fun\n"
                }
            ]    
        }